### ISSUE TITLE
add nice access denied message with instructions how to apply for access

### ISSUE THREAD

**Issue by volodymyrss** [cta-epfl/downloadservice#12]
* [x] make a nice message explaining why access is blocked
* [x] figure out what happens when user is logging in but the account is not approved - it returns 403 too, the same I guess, need to explain
* [x] redirect to form for requesting resources and substitute identity with which the user logged in

**Comment by volodymyrss** [comment]
Since it's done I think, could you add a screenshot here, link the branch which made the fix, and we can close this? Thanks!

**Comment by Ph0tonic** [comment]
So there is no commit in this repository. Changes were made directly in https://github.com/cta-epfl/k8s-hub
Here is the result :
![image](https://github.com/cta-epfl/downloadservice/assets/5320541/a5f9505f-1d46-47f7-a176-1207690e7ed2)

**Comment by volodymyrss** [comment]
In github you can also link issues to PRs from other repositories. But I guess it's not in a PR there, right?

Ok, this is something but XXX - do we set in config?

**Comment by Ph0tonic** [comment]
So to configure XXX, we just need to update this file:
- https://github.com/cta-epfl/k8s-hub/blob/main/templates/error.html
No, it's not a PR.

**Comment by volodymyrss** [comment]
Yeah, but that's not especially configurable. Would be better to have some administrative contact value.
By the way the reason why I added it to this service because I thought we could add some form to collect info. But, I guess we can do it differently a bit, I will make a change.

**Comment by Ph0tonic** [comment]
> This will be for access denied for jupyterhub itself, right? And for service access what happens?
So I tested it for access denied with services. For access denied on JupyterHub, It should be the same.

**Comment by volodymyrss** [comment]
Could you check if it is the same? probably.
When accessing with API it will not be too obvious unless `ctadata` client is used. Well, anyway, this is fine, if we check if works correctly for both hub and service.

**Comment by Ph0tonic** [comment]
So I am not sure how to test it because by default when not connected, it will redirect to the login form. But the way we customised this form, it will be displayed for all 403 error codes.

**Comment by Ph0tonic** [comment]
For use with ctadata, we will need some additional changes, because ctadata doesn't display any HTML.

**Comment by volodymyrss** [comment]
We'd need to either strip html for console or just return another message for different Accept mime. Not sure if jupyterhub can do that? What if you access with curl, can you make it return json?

**Comment by volodymyrss** [comment]
There is another issue I remembered why this was more complex: people come with their accounts but they might not even know how they are identified by the platform. It's not always email. It would be good to pass this identity into the request form.

We might also need some custom request form, that one is our "agreed version" but it's a bit generic.

**Comment by volodymyrss** [comment]
![image](https://github.com/cta-epfl/downloadservice/assets/3909535/50bd3f1c-62c0-4790-9a8c-811fb95f85b8)

to give an idea what I mean in the last comment, from this 403 message user has no idea what user id to communicate to admins and the admins do not know which user is denied access, except by looking into hub container log. The id depends on the provider and they are all different.

- [ ] write to user explicitly which is their user id in this case
- [ ] while sending to the request form, maybe substitute the account name?..
- [ ] send a sentry message to us whenever user is denied? in principle this should never happen

**Comment by Ph0tonic** [comment]
If we want to have prefilled fields, I found this link which explains how to proceed:
- https://www.labnol.org/prefilled-google-forms-200601

However, I am missing some permissions to be able to generate this link. If you could provide me with the link ti would be great and we could then directly include the `user_id`.

**Comment by volodymyrss** [comment]
Ok, thanks. On second thought, and since it looks like we do not have a suitable field in the form to fill with particular, let's not do this part. Actually we should be able to deduce the account from email.
Also this kind of log can go into logging system not sentry.
