### ISSUE TITLE
need a way to upload personal user certificate or shared robot certificate with downloadservice API, not k8s API

### ISSUE THREAD

**Issue by volodymyrss** [cta-epfl/downloadservice#28]
note that this issue here is another option, to allow jupyterhub users to upload their own proxy certificates through downloadservice API.  This was we can use their own credentials too.

On the other hand, the same mechanism can be used to upload shared robot certificate, only admin user should be allowed to do this. This is much easier than using k8s api.

**Comment by Ph0tonic** [comment]
Which mechanism should we put in place to ensure the security of certificates ? I propose that when a user upload a certificate, we generate a new one signed with the provided certificated with a limited timestamp. This way, even if the user do a mistake, his certificate is never stored online. We can implement this mechanism on both sides. We could develop a small client which processes the certificate and on the server side, we just ensure that only short-term validity certificates are uploaded to prevent any leak of original certificates.
What do you think ?

**Comment by Ph0tonic** [comment]
> > Which mechanism should we put in place to ensure the security of certificates ? I propose that when a user upload a certificate, we generate a new one signed with the provided certificated with a limited timestamp. This way, even if the user do a mistake, his certificate is never stored online. We can implement this mechanism on both sides. We could develop a small client which processes the certificate and on the server side, we just ensure that only short-term validity certificates are uploaded to prevent any leak of original certificates. What do you think ?
> 
> If a long-lasting certificate is uploaded it should be rejected and nothing should be done. Mistake should be made clear making another reminder that personal certificate should never be uploaded anywhere without very good reason (if ever).

For sure !

> If short-term certificate is uploaded I do really see why is it useful to make another certificate with the same scope and validity time?

What I propose is to automate the generation of the short-term certificate on the client side. The idea being that the user call this new client with it's certificate and then it will automatically generate a shor-term certificate which will be uploaded. This way, it's easy for him and he only need to launch a single command to update the remote certificate.

**Comment by volodymyrss** [comment]
> What I propose is to automate the generation of the short-term certificate on the client side. The idea being that the user call this new client with it's certificate and then it will automatically generate a shor-term certificate which will be uploaded. This way, it's easy for him and he only need to launch a single command to update the remote certificate.

There are multiple tools to do that (e.g. voms-proxy-init and arcproxy) and users are familiar with them since it's very common to work with short proxy certificates in this use case. The tools also take care of additional certificate extensions allowing to restrict certificate scope by VO (see VOMS).

**Comment by Ph0tonic** [comment]
Ok, I will have a look at those tools.
First I will start with the backend on `downloadservice` 👍

**Comment by Ph0tonic** [comment]
Small question, when a user upload it's certificate, should he upload a cabundle as well ? Or can we rely on the cabundle file provided ?

**Comment by volodymyrss** [comment]
> Small question, when a user uploads its certificate, should he upload a cabundle as well ? Or can we rely on the cabundle file already provided ?

CA Bundle is provided by us, it's important that it is so, it reflects our chain of trust, which we establish ourselves.
The users provide their own identity then, and when uploaded we can also verify that their certificates are valid with our CA bundle.
